# Concentration dependent elastic constants

Here we demonstrate the new `SQSElasticConstantsList` job, which gets elastic constants as a function of chemical composition.

This job works by using special quasirandom structures (implemented by Dominik Gehringer and Jan Janssen) to create cells with the requested chemical composition from a base crystal structure. These are then evaluated for their elastic constants (implemented by Yuri Lysogorskiy). These are fully relaxed and the basic output is the chemical composition and full 6x6 elastic matrix. (More detailed output is available from the underlying `SQSElasticConstants` job stored in HDF5, but user-friendly bindings are not currently implemented.)

These components were assembled together in a single job (implemented by Liam Huber) that takes a list of dictionaries giving the desired chemical compositions (e.g. `{'Al': 0.95, 'Mg': 0.04, '0': 0.01}` for 95% Aluminium 4% Magnesium and 1% vacancies) and three reference jobs: a `ref_ham` which says how the structures should be interpreted for forces and energies (e.g. a Lammps job with a particular potential) -- the structure of this job provides the base crystal upon which the chemical compositions are imposed -- and `ref_sqs` and `ref_elastic` which hold the input parameters for the SQS and elastic constant calculation components.

The current implementation only facilitates modal run modes and is not heavily tested. The example below takes less than 30 minutes on a single core, so for the purposes of demonstration this is not a serious limitation.

In [1]:
%matplotlib inline

In [2]:
from pyiron import Project
import numpy as np
import matplotlib.pyplot as plt
from elastic import ElasticMatrixJob
from damaskjob import DAMASKjob
import seaborn as sns
import yaml

In [3]:
pr = Project('elastic_pipeline')
pr.remove_jobs_silently(recursive=True)

## Run the calculation

Our test system will be Al with dilute Mg (up to 2%). Here we define the reference jobs, give our desired compositions.

Feedback on the most user-friendly way to take chemical composition input (while still being fully flexible in allowed compositions!) is welcome -- this code is still in development.

In [4]:
lmp_mini = pr.create_job(pr.job_type.Lammps, 'lammps_mini')
lmp_mini.structure = pr.create_ase_bulk('Al', cubic=True).repeat(5)
lmp_mini.potential = 'Al_Mg_Mendelev_eam'
lmp_mini.calc_minimize(pressure=0.0)
lmp_mini.run()

The job lammps_mini was saved and received the ID: 1


In [5]:
sqs_job_al = pr.create_job(
    job_type=pr.job_type.SQSJob, 
    job_name="sqs_job_al"
)
sqs_job_al.structure = lmp_mini.get_structure()
sqs_job_al.input['iterations'] = 1000
master_al = sqs_job_al.create_job(
    job_type=pr.job_type.SQSMaster, 
    job_name="master_al"
)

master_al.input["fraction_lst"] = [0.005, 0.01, 0.015, 0.02]
master_al.input["species_one"] = "Mg"
master_al.input["species_two"] = "Al"
master_al.run()

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyiron_base/generic/parameters.py:860: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  self._dataset[col] = np.array(self._dataset[col]).tolist()


The job master_al was saved and received the ID: 2
The job sqs_0_005 was saved and received the ID: 3
Mole fractions were corrected to: {'Mg': 0.004, 'Al': 0.996}
Threads used: 1
The job sqs_0_01 was saved and received the ID: 4
Threads used: 1
The job sqs_0_015 was saved and received the ID: 5
Mole fractions were corrected to: {'Mg': 0.016, 'Al': 0.984}
Threads used: 1
The job sqs_0_02 was saved and received the ID: 6
Threads used: 1


In [6]:
concentration_lst = [0.0] + [0.005, 0.01, 0.015, 0.02]

In [7]:
structure_lst = [lmp_mini.get_structure()] + master_al.list_of_structures

In [8]:
[s.get_chemical_formula() for s in structure_lst]

['Al500', 'Al498Mg2', 'Al495Mg5', 'Al492Mg8', 'Al490Mg10']

In [9]:
for s in structure_lst:
    lmp_template = pr.create_job(pr.job_type.Lammps, 'lammps_tmp')
    lmp_template.potential = 'Al_Mg_Mendelev_eam'
    lmp_template.server.run_mode.interactive = True
    lmp_template.interactive_enforce_structure_reset = True
    lmp_template.structure = s
    elastic = lmp_template.create_job(ElasticMatrixJob, 'elastic_' + s.get_chemical_formula())
    elastic.input['num_of_points'] = 5
    elastic.input['fit_order'] = 2
    elastic.input['eps_range'] = 0.005
    elastic.input['relax_atoms'] = True
    elastic.input['sqrt_eta'] = True
    elastic.run()

The job elastic_Al500 was saved and received the ID: 7
The job elastic_Al500_lammps_tmp was saved and received the ID: 8


/srv/conda/envs/notebook/lib/python3.7/site-packages/pyiron/lammps/interactive.py:363: UserWarning: Warning: setting upper trangular matrix might slow down the calculation
  "Warning: setting upper trangular matrix might slow down the calculation"


The job elastic_Al498Mg2 was saved and received the ID: 9
The job elastic_Al498Mg2_lammps_tmp was saved and received the ID: 10
The job elastic_Al495Mg5 was saved and received the ID: 11
The job elastic_Al495Mg5_lammps_tmp was saved and received the ID: 12
The job elastic_Al492Mg8 was saved and received the ID: 13
The job elastic_Al492Mg8_lammps_tmp was saved and received the ID: 14
The job elastic_Al490Mg10 was saved and received the ID: 15
The job elastic_Al490Mg10_lammps_tmp was saved and received the ID: 16


## post-processing the data

The output of the job is stored to HDF5. To verify this, and since the actual calculation may be done at a different time than the results are analyzed, we demonstrate this by loading the job.

There is also a little bit of annoying post-processing to get it all formatted as nice numpy arrays. Some of this is reasonable (like the need to explicitly add 0% Mg to the first chemistry -- we wouldn't want to list *everything that's not there*!), some is "not my fault" (like the way the InputList class mangles our chemistry dictionary on saving it to HDF), and some needs nicer helper functions in the future (like the ability to explicity ask for "C12" and get it by that string).

In [10]:
pr.job_table()

id    status chemicalformula                           job  \
0    1  finished           Al500                   lammps_mini   
1    2  finished           Al500                     master_al   
2    3  finished           Al500                     sqs_0_005   
3    4  finished           Al500                      sqs_0_01   
4    5  finished           Al500                     sqs_0_015   
5    6  finished           Al500                      sqs_0_02   
6    7  finished           Al500                 elastic_Al500   
7    8  finished           Al500      elastic_Al500_lammps_tmp   
8    9  finished        Al498Mg2              elastic_Al498Mg2   
9   10  finished        Al498Mg2   elastic_Al498Mg2_lammps_tmp   
10  11  finished        Al495Mg5              elastic_Al495Mg5   
11  12  finished        Al495Mg5   elastic_Al495Mg5_lammps_tmp   
12  13  finished        Al492Mg8              elastic_Al492Mg8   
13  14  finished        Al492Mg8   elastic_Al492Mg8_lammps_tmp   
14  15  finished       Al490Mg10             elastic_Al490Mg10   
15  16  finished       Al490Mg10  elastic_Al490Mg10_lammps_tmp   

                           subjob    projectpath  \
0                    /lammps_mini  /home/jovyan/   
1                      /master_al  /home/jovyan/   
2                      /sqs_0_005  /home/jovyan/   
3                       /sqs_0_01  /home/jovyan/   
4                      /sqs_0_015  /home/jovyan/   
5                       /sqs_0_02  /home/jovyan/   
6                  /elastic_Al500  /home/jovyan/   
7       /elastic_Al500_lammps_tmp  /home/jovyan/   
8               /elastic_Al498Mg2  /home/jovyan/   
9    /elastic_Al498Mg2_lammps_tmp  /home/jovyan/   
10              /elastic_Al495Mg5  /home/jovyan/   
11   /elastic_Al495Mg5_lammps_tmp  /home/jovyan/   
12              /elastic_Al492Mg8  /home/jovyan/   
13   /elastic_Al492Mg8_lammps_tmp  /home/jovyan/   
14             /elastic_Al490Mg10  /home/jovyan/   
15  /elastic_Al490Mg10_lammps_tmp  /home/jovyan/   

                             project                  timestart  \
0                  elastic_pipeline/ 2020-11-04 13:46:57.440146   
1                  elastic_pipeline/ 2020-11-04 13:47:00.051413   
2   elastic_pipeline/master_al_hdf5/ 2020-11-04 13:47:00.504656   
3   elastic_pipeline/master_al_hdf5/ 2020-11-04 13:47:01.686025   
4   elastic_pipeline/master_al_hdf5/ 2020-11-04 13:47:02.800456   
5   elastic_pipeline/master_al_hdf5/ 2020-11-04 13:47:03.927949   
6                  elastic_pipeline/ 2020-11-04 13:47:07.948217   
7                  elastic_pipeline/ 2020-11-04 13:47:09.031784   
8                  elastic_pipeline/ 2020-11-04 13:47:16.864423   
9                  elastic_pipeline/ 2020-11-04 13:47:17.811738   
10                 elastic_pipeline/ 2020-11-04 13:47:33.755828   
11                 elastic_pipeline/ 2020-11-04 13:47:35.600153   
12                 elastic_pipeline/ 2020-11-04 13:48:34.050450   
13                 elastic_pipeline/ 2020-11-04 13:48:36.239618   
14                 elastic_pipeline/ 2020-11-04 13:49:36.466351   
15                 elastic_pipeline/ 2020-11-04 13:49:38.511145   

                     timestop  totalcputime  \
0  2020-11-04 13:46:58.129645           0.0   
1  2020-11-04 13:47:05.285411           5.0   
2  2020-11-04 13:47:01.277787           0.0   
3  2020-11-04 13:47:02.337110           0.0   
4  2020-11-04 13:47:03.542456           0.0   
5  2020-11-04 13:47:05.267329           1.0   
6  2020-11-04 13:47:16.517777           8.0   
7  2020-11-04 13:47:15.496906           6.0   
8  2020-11-04 13:47:33.385197          16.0   
9  2020-11-04 13:47:32.691423          14.0   
10 2020-11-04 13:48:33.679584          59.0   
11 2020-11-04 13:48:32.927744          57.0   
12 2020-11-04 13:49:36.083473          62.0   
13 2020-11-04 13:49:35.271879          59.0   
14 2020-11-04 13:50:36.260397          59.0   
15 2020-11-04 13:50:35.518672          57.0   

                                                        

In [11]:
def filter_function(job): 
    return "elastic_" in job.job_name and "lammps_tmp" not in job.job_name

In [12]:
def get_c11(job):
    return job["output/elasticmatrix"]["C"][0,0]

def get_c12(job):
    return job["output/elasticmatrix"]["C"][0,1]

def get_c44(job):
    return job["output/elasticmatrix"]["C"][3,3]

In [13]:
table = pr.create_table()

In [14]:
table.filter_function = filter_function
table.add["C11"] = get_c11
table.add["C12"] = get_c12
table.add["C44"] = get_c44

In [15]:
table.run()

 20%|██        | 1/5 [00:00<00:00,  7.45it/s]

The job table was saved and received the ID: 17


100%|██████████| 5/5 [00:01<00:00,  2.67it/s]
2020-11-04 13:50:38,432 - pyiron_log - WARNING - The job table is being loaded instead of running. To re-run use the argument 'delete_existing_job=True in create_job'


In [16]:
df_data = table.get_dataframe()
df_data

job_id         C11        C12        C44
0       7  110.193270  61.752630  32.746691
1       9  111.508311  62.822413  33.243939
2      11  113.094999  64.540009  34.095902
3      13  114.615533  66.226981  34.914956
4      15  115.806558  67.190895  35.459355

## Analysis

Finally, let's use numpy to make a polynomial fit of our elastic constants to alloying concentration and visualize the results.

Note: pure-Al data lines up very nicely with the pure Al elastic constants [reported on the NIST website for this potential](https://www.ctcms.nist.gov/potentials/entry/2009--Mendelev-M-I-Asta-M-Rahman-M-J-Hoyt-J-J--Al-Mg/2009--Mendelev-M-I--Al-Mg--LAMMPS--ipr1.html). I don't have a good sense for exactly what <2% Mg should be doing, but at least there are no sharp changes. Sanity check passed.

In [17]:
concentrations = np.array(concentration_lst)

In [18]:
C11_data = df_data["C11"].values
C12_data = df_data["C12"].values
C44_data = df_data["C44"].values

In [19]:
fit_degree = 2
C11_fit = np.polyfit(concentrations, C11_data, deg=fit_degree)
C12_fit = np.polyfit(concentrations, C12_data, deg=fit_degree)
C44_fit = np.polyfit(concentrations, C44_data, deg=fit_degree)
c = np.linspace(concentrations.min(), concentrations.max(), 100)  # 'Continuous' concentration

In [20]:
# p(x) = p[0] * x**deg + ... + p[deg]
print(C11_fit)
print(C12_fit)
print(C44_fit)

[-897.67343324  304.62943377  110.13209068]
[-692.46413146  299.47124433   61.61574273]
[175.41012385 138.41868899  32.68166982]


In [21]:
for color, data, fit, label in zip(
    sns.color_palette(n_colors=3), 
    [C11_data, C12_data, C44_data], 
    [C11_fit, C12_fit, C44_fit],
    ['C11', 'C12', 'C44']
):
    plt.scatter(concentrations, data, color=color)
    plt.plot(c, np.polyval(fit, c), color=color, label=label)
plt.xlabel('Mg concentration')
plt.ylabel('Elastic constant (GPa)')
plt.legend()
plt.show()

# DAMASK Simulations
The steps include, defining:
- geometries
- grains
- loading
- material properties based on the atomistically-evaluated 
- perfoming simulations

In [22]:
concentrations

array([0.   , 0.005, 0.01 , 0.015, 0.02 ])

In [23]:
with open('Examples/material.yaml') as f:
    material = yaml.load(f, Loader=yaml.FullLoader)
with open('Examples/tensionX.load') as f:
    tension = f.readlines()

In [ ]:
job_lst = []
for i,c in enumerate(concentrations):
    job = pr.create_job(DAMASKjob, "damask_" + 'mg_{}'.format(int(c*100)))
    job.material = material
    job.tension = tension
    job.input['C11'] = float(np.polyval(C11_fit, c))
    job.input['C12'] = float(np.polyval(C12_fit, c))
    job.input['C44'] = float(np.polyval(C44_fit, c))
    job.run()
    job_lst.append(job)

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyiron_base/generic/parameters.py:860: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  self._dataset[col] = np.array(self._dataset[col]).tolist()


The job damask_mg_0 was saved and received the ID: 18


## Post-processing DAMASK simulations
- Von-Mises stress for each case is calculated
- The Stress-strain data is evaluated for each case


In [ ]:
stresses, strains = [], []
for job in job_lst: 
    damask_results = job.output
    damask_results.add_Cauchy()
    damask_results.add_strain_tensor()
    damask_results.add_Mises('sigma')
    damask_results.add_Mises('epsilon_V^0.0(F)')
    damask_results.add_calculation('avg_sigma',"np.average(#sigma_vM#)")
    damask_results.add_calculation('avg_epsilon',"np.average(#epsilon_V^0.0(F)_vM#)")
    damask_results.save_vtk(['sigma','epsilon_V^0.0(F)','sigma_vM','epsilon_V^0.0(F)_vM'])
    stresses.append(job.eval_stress())
    strains.append(job.eval_strain())

## Visualization
### Von-Mises Stress

In [ ]:
import pyvista as pv
inc=20
mesh = pv.read(job.output_file.split('.')[0] + f'_inc{inc}.vtr')  #enter the file name you wish to view

In [ ]:
from itkwidgets import view
import itk
mesh

In [ ]:
pl = pv.PlotterITK()
pl.add_mesh(mesh)
pl.show()

### Stress-strain curve

In [ ]:
i = 0;
stresses[0]= eval_stress(job_file[0])
stresses[1]= eval_stress(job_file[1])
stresses[2]= eval_stress(job_file[2])
colors = ['r','g','b']
#for color, strain, stress, c in zip(colors, strains, stresses, concentrations):
plt.plot(strains[0], stresses[0], 'r', linewidth=2, label = 'Mg={}%'.format(0*100))
plt.plot(strains[1], stresses[1], 'b', linestyle="None",marker = 'o' ,label = 'Mg={}%'.format(0.01*100))
plt.plot(strains[1], stresses[2], 'g', linestyle="None",marker = '*' ,label = 'Mg={}%'.format(0.01*100))
#plt.ylim(90, 95)
plt.grid(True)
plt.xlabel('$Strain$')
plt.ylabel('Stress- MPa')
plt.legend( loc='lower right')
plt.title("Stress-Strain")
 #   i= i+1;